export const DEGREES = [
  { label: 'MBBS', value: 'MBBS' },
  { label: 'BDS', value: 'BDS' },
  { label: 'FCPS', value: 'FCPS' },
  { label: 'MCPS', value: 'MCPS' },
  { label: 'MD', value: 'MD' },
  { label: 'MS', value: 'MS' },
  { label: 'MPhil', value: 'MPhil' },
  { label: 'MPH', value: 'MPH' },
  { label: 'Diploma (DCH, DGO, DLO, etc.)', value: 'Diploma' },
  { label: 'PhD', value: 'PhD' },
  { label: 'FRCS', value: 'FRCS' },
  { label: 'MRCP', value: 'MRCP' },
  { label: 'MRCOG', value: 'MRCOG' },
  { label: 'FACP', value: 'FACP' },
  { label: 'Fellowship Programs', value: 'Fellowship' },
];

export const SPECIALIZATIONS = [
  { label: 'Medicine', value: 'Medicine' },
  { label: 'Internal Medicine', value: 'Internal Medicine' },
  { label: 'Cardiology', value: 'Cardiology' },
  { label: 'Endocrinology', value: 'Endocrinology' },
  { label: 'Gastroenterology', value: 'Gastroenterology' },
  { label: 'Nephrology', value: 'Nephrology' },
  { label: 'Neurology', value: 'Neurology' },
  { label: 'Pulmonology', value: 'Pulmonology' },
  { label: 'Rheumatology', value: 'Rheumatology' },
  { label: 'Hematology', value: 'Hematology' },
  { label: 'General Surgery', value: 'General Surgery' },
  { label: 'Cardiothoracic Surgery', value: 'Cardiothoracic Surgery' },
  { label: 'Neurosurgery', value: 'Neurosurgery' },
  { label: 'Plastic Surgery', value: 'Plastic Surgery' },
  { label: 'Vascular Surgery', value: 'Vascular Surgery' },
  { label: 'Pediatric Surgery', value: 'Pediatric Surgery' },
  { label: 'Urology', value: 'Urology' },
  { label: 'Gynecology', value: 'Gynecology' },
  { label: 'Obstetrics & Gynecology', value: 'Obstetrics & Gynecology' },
  { label: 'Reproductive Medicine', value: 'Reproductive Medicine' },
  { label: 'Pediatrics', value: 'Pediatrics' },
  { label: 'Neonatology', value: 'Neonatology' },
  { label: 'Pediatric Cardiology', value: 'Pediatric Cardiology' },
  { label: 'Pediatric Neurology', value: 'Pediatric Neurology' },
  { label: 'Radiology', value: 'Radiology' },
  { label: 'Pathology', value: 'Pathology' },
  { label: 'Anesthesiology', value: 'Anesthesiology' },
  { label: 'Nuclear Medicine', value: 'Nuclear Medicine' },
  { label: 'Dermatology', value: 'Dermatology' },
  { label: 'Psychiatry', value: 'Psychiatry' },
  { label: 'Ophthalmology', value: 'Ophthalmology' },
  { label: 'ENT (Otolaryngology)', value: 'ENT' },
  { label: 'Orthopedics', value: 'Orthopedics' },
  { label: 'Oncology', value: 'Oncology' },
  { label: 'Dentistry', value: 'Dentistry' },
  { label: 'Physical Medicine & Rehabilitation', value: 'Physical Medicine & Rehabilitation' },
  { label: 'Family Medicine', value: 'Family Medicine' },
  { label: 'Emergency Medicine', value: 'Emergency Medicine' },
  { label: 'Critical Care Medicine', value: 'Critical Care Medicine' },
  { label: 'Infectious Disease', value: 'Infectious Disease' },
];
